[package]
name = "pmd_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24", features = ["png"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
