[package]
name = "pmd_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24", features = ["png"] }
oxipng = "8.0"
twox-hash = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap =  { version = "4.5", features = ["derive"] }
